---
title: "MS Workflow Step 1"
author: "BT"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
source("assessFeatures.R")
source("uploadfile.R")
source("normality_check.R")
source("normalization.R")
source("univariate.R")
```

```{r setup_run}
# user declared variables
raw_data_file <- "D:/2021_Checco/Unnormalized peak areas/Unnormalized all protein-peptides No Dup.csv"

FDR <- 0.05
LOG2FC <- 0

```

upload file 
```{r}
fh <- upload.file(raw_data_file, 1, 2:88)
labels_d1 <- as.matrix(fh$Label); row.names(labels_d1) <- row.names(fh); colnames(labels_d1) <- "Label"
print(sum(fh==0))
write(paste("Missing signal raw file:", sum(fh==0)), "missingSignals.txt", append = TRUE)
```

assess features; return present features
```{r}
raw.file <- presence.absence(fh)[,-(1:2)]
head(raw.file)
print(sum(is.na(raw.file)))
write(paste("Missing signal before imputation:", sum(is.na(raw.file))), "missingSignals.txt", append = TRUE)
```

Impute missing values
```{r}
imputed_meta_d1 <- impute::impute.knn(as.matrix(raw.file), k = 7, rowmax = 0.5, 
                              colmax = 0.8, maxp = 1500)

imputed_d1 <- as.data.frame(imputed_meta_d1[["data"]], colnames = TRUE)
MASS::truehist(unlist(imputed_d1), main = "Imputed", nbins = 50)
write.csv(imputed_d1, "imputedData.csv")
print(sum(imputed_d1==0))
write(paste("Missing signal after imputation:", sum(imputed_d1==0)))
```

PCA
```{r}
## PCA
library(ggplot2)
library(pcaMethods)

imputed_d2 <- rbind.data.frame(t(labels_d1), imputed_d1)
pc1 <- pca(t(imputed_d1), scale = "pareto")
pc1merged <- merge(t(imputed_d2), scores(pc1), by=0)

pdf("PCA-Initial.pdf")
ggplot(pc1merged, aes(PC1, PC2, colour=Label)) +
  geom_point() +
  stat_ellipse() +
  xlab(paste("PC1", round((pc1@R2[1] * 100), digits = 1), "% of the variance")) +
  ylab(paste("PC2", round((pc1@R2[2] * 100), digits = 1), "% of the variance"))
dev.off() 
```
# todo: add batch correction - BT

log 2 transformation
```{r}
log2_d1 <- log2(type.convert(imputed_d1)) ## log2 transformation

pdf("Histogram-log2transformedNoDup.pdf")
MASS::truehist(unlist(log2_d1), main = "Log2 Transformed", nbins = 50)
dev.off()

log2_d1 <- rbind.data.frame(t(labels_d1), log2_d1)
```

normality check
```{r check_norm}
normality_check(log2_d1)
```

do normalization
```{r do_norm}
norm_log2_d1 <- normalization(log2_d1)
```

do univariate
```{r do_univariate}
# first do data formatting
d3_mod <- t(norm_log2_d1) %>%
  as_tibble() %>%
  mutate(across(-Label, as.numeric)) %>%
  rename_with(str_trim)

# then do univariate analysis
uni_res <- do_univariate(d3_mod)
```

univariate visualization
```{r uni_visualization}


# format univariate results tibble for plotting
uni_res <- uni_res %>%
  rowwise() %>%
  mutate(padj = min(c(BHT, BHW))) %>%
  # get the lowest padj
  ungroup() %>%
  mutate(`-log10padj` = -log(padj))

# get DE features only tibble
uni_res_filt <- uni_res %>%
  # filter(BHT < fdr | BHW < fdr) %>%
  filter(BHT < fdr & BHW < fdr) %>%
  mutate(status = if_else("FC(log2)" < 0, "Down", "Up"))


# 1) volcano plot
deseq2_volcano(uni_res, uni_res_filt,
  fdr = fdr, log2fc = log2fc,
  "variable", padj_col = "padj", log2fc_col = "FC(log2)"
)

# -----------------------------------------------------------------------------
# prep the annotation for hm
anno <- data.frame(Label = as.factor(t(norm_log2_d1)[, "Label"]))

# prep the transformed matrix for hm
d1_mod <- norm_log2_d1 %>%
  rownames_to_column("variable")

# 2) heatmap/multiple heatmaps?
deseq2_hm(d1_mod, uni_res_filt, "variable", anno,
  top_n = NULL, col_order = NULL,
  save = FALSE, padj_col = NULL
)

# -----------------------------------------------------------------------------
# 3) venn diagram between t-test and wilcox test
plot_set1 <- uni_res %>%
  filter(BHT < fdr) %>%
  pull(variable)
plot_set2 <- uni_res %>%
  filter(BHW < fdr) %>%
  pull(variable)
# v_data <- list("T Test" = plot_set1, "Wilcoxon Test" = plot_set2)
v_data <- list("Wilcoxon Test" = plot_set2, "T Test" = plot_set1)

v1 <- make_venn(v_data)
ggsave("univariate_venn.png", v1, device = "png", width = 6, height = 6)
ggsave("univariate_venn.pdf", v1, device = "pdf", width = 6, height = 6)

```
